- .github/renovate.json
Configuration preset defined [here]
[here]: https://docs.renovatebot.com/presets-config/#configjs-app
Ticket: 0
> chore: enable renovate

- .github/workflows/release.yml
> ci: configure tokens

- src/args.rs
- src/default_branch.rs
- src/main.rs
- src/sanitize_git_branch_name.rs
> refactor: parse into domain type using clap

- src/main.rs
> chore: remove todo

- src/issue.rs
At least mostly, this only supports closing one ticket.
Closes #33
> feat: support GitHub closes syntax

- src/main.rs
> fix: correctly check out the original ref

- src/args.rs
- src/default_branch.rs
> refactor: reduce verbosity of visibility

- src/args.rs
> refactor: use default values from cargo manifest

- .github/workflows/ci.yml
- .github/workflows/release.yml
> ci: ensure only one release workflow runs concurrently

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/default_branch.rs
- src/interact.rs
- src/issue.rs
- src/main.rs
> feat: add --choose to select issues to create PRs for

- src/issue.rs
- src/main.rs
> fix: sort list of issues with --choose flag

- README.md
> docs: refresh the readme

- .gitignore
- flake.lock
- flake.nix
- src/main.rs
- src/user_config.rs
- support building the binary with `nix build`
- use fenix for nightly Rust toolchain
- use alejandra formatter
> chore: fix nix flake

- src/args.rs
> fix: add information to help strings

- .github/workflows/ci.yml
> ci: simplify invocation

- .github/workflows/ci.yml
> ci: run flake checks

- .github/workflows/ci.yml
h/t to @dpc for [this lead](https://github.com/rikhuijzer/cache-install/issues/2#issuecomment-1192268125)
Closes #87
> ci: cache nix flake attributes

- README.md
> docs: document the hub requirement

- Cargo.lock
- Cargo.toml
to wrap long help messages.
Ticket: 0
> chore: add clap feature wrap_help

- Cargo.toml
- src/default_branch.rs
> fix: add better error message when hub is not configured

- src/main.rs
> fix: support invocation from subdirectory of git repository

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/issue.rs
- src/issue_group.rs
- src/main.rs
- src/sanitized_args.rs
> feat: clean up output with terminal ui
